<?php
/**
 * Created by : PhpStorm
 * User: zhang
 * Date: 2019/12/25
 * Time: 11:26
 */

namespace exception;


use think\exception\Handle;
use think\Response;
use Throwable;

class BaseHandler extends Handle
{
    public function render($request, Throwable $e): Response
    {
        if($e instanceof  BaseExceptions){
            return Response::create(['code'=>$e->getCode(),'msg'=>$e->getMessage()],'json');
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}